# Configuration file for pipeline

# Mapping for grouping clades into clusters
clade_cluster:
  {'all': ['root'],
 }

 # Mapping for grouping clades into clusters
cluster_founder:
  all: root

overwrite: true

output_dir: results_test_hiv_pol_with_rna
input_dir: "/home/sasha/Downloads/tmp"

# How to handle nucleotide sites that overlap among sites: exclude them from
# amino-acid fitness estimates or retain those sites in estimates. If retained, estimates
# can be confounded by not knowing which gene the selection is acting on.
gene_overlaps:
  exclude: []
  retain: []
    # - [M2-1, M2-2] # add later for RSV

# Pseudocount for calculating amino-acid fitnesses
fitness_pseudocount: 0.5

# Include RNA secondary structure in mutation rate model (requires 'unpaired' column in data)
use_rna_structure: true

# Minimum number of sites per motif for inclusion in exploratory plots
plot_min_sites: 5

# Genes order on the viral genome
genes: all

# Define common names of Nexstrain clades
clade_synonyms:
    root: root

# minimal domain for amino-acid fitness heatmap
aa_fitness_heatmap_minimal_domain: [-6, 2] 

# Default minimum expected count for amino-acid fitness estimates
min_predicted_count: 1

# minimum count for correlation calculation
cluster_corr_min_count: 1

# # For GitHub Pages docs of plots
# docs_url: https://neherlab.github.io/SARS2-refined-fitness  # base URL for GitHub pages site
docs_plot_annotations: data/docs_plot_annotations.yaml  # lists plots and their annotations